spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.212.34:3306/campus_management?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: "0903"

  redis:
    host: 124.221.212.34
    port: 6379
    password: "033418"
    database: 1
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱，已开通POP3/SMTP服务的邮箱，也就是你自己的
    username: 2637432237@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: abqaflodaxnbebji
    # 发送人昵称
    nickname: Answer
    # 端口号465或587（QQ邮箱发送邮件仅支持587端口协议）
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  servlet:
    multipart:
      max-file-size: 500MB     #单文件上传大小
      max-request-size: 500MB  #总文件



file:
  upload:
    #文件保存路径
    path: /home/answer/excel_all/
#    path: //D://test//
server:
  port: 8081
  ssl:
    key-store: classpath:campus.abmy.online.pfx
    key-store-password: 47otrq64991
#    key-alias: tomcat
#    enabled: true
#    key-store-type: JKS

